MangaWeb/MangaWeb/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#LINKS QUE DESEES PONER

MangaWeb/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns= [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('', views.IndexView.as_view(), name='home'),
    path('blog/', views.BlogView.as_view(), name='blogs'),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name='blog'),
    path('review/', views.ReviewView.as_view(), name='reviews'),
    path('review/<slug:slug>', views.ReviewDetailView.as_view(), name='review'),
    path('blogaddinfo/', views.BlogAddInfo.as_view(), name='blogaddinfo'),
    path('reviewaddinfo/', views.ReviewAddInfo.as_view(), name='reviewaddinfo'),
    
]

#APARTADO PARA USAR LOS URLS CREADOS A TRAVÉS DE UN NOMBRE Y QUE TE REDIRIGA AL ENLACE SELECCIONADO Y ANTERIORMENTE CREADO, EN ESTE CASO LOS DE LOS HTML

MangaWeb/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

class BLOG(models.Model):

    class Meta:
        verbose_name_plural = 'BLOGS'
        verbose_name = 'BLOG'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="BLOG")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(BLOG, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/BLOG/{self.slug}"

class REVIEW(models.Model):

    class Meta:
        verbose_name_plural = 'REVIEWS'
        verbose_name = 'REVIEW'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="REVIEW")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(REVIEW, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/REVIEW/{self.slug}"

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

# CREAR LOS ESPACIOS DE LO QUE TU QUIERAS LOGRAR DE MODELO, EN ESTE CASO SE HIZO BLOG, REVIEW & UserProfile

MangaWeb/main/forms.py
from dataclasses import field, fields
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from main.models import BLOG, REVIEW



class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		fields = ('name', 'email', 'message',)

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']

class BlogForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '',
			}))
	body = forms.CharField(max_length=1000, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '',
			}))
	image = forms.ImageField()


	class Meta:
		model = BLOG
		fields = ['author','name','description','body','image']


class ReviewForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '',
			}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '',
			}))
	body = forms.CharField(max_length=1000, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '',
			}))
	image = forms.ImageField()


	class Meta:
		model = REVIEW
		fields = ['author','name','description','body','image']


#Crea los Formularios ya existentes de DJANGO forms, usa la clase Meta y pide los atributos que quieras que tengamos existentes de los modelos (en este caso REVIEW y BLOG)

MangaWeb/main/views.py
from django.shortcuts import render
from django.contrib import messages

from .models import (
    BLOG,
    REVIEW,
    
)

from  django.views import generic
from . forms import BlogForm, ContactForm, CreateUserForm, ReviewForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

def registerPage(request):
    context= None
    if request.user.is_authenticated:
        return redirect("main:home")
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Su Cuenta ha sido creada de forma Satisfactoria')

                return redirect('main:login')

        context= {'form':form}
        return render(request, 'main/signup.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect("main:home")
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("main:home")
            else:
                messages.info(request, 'Username OR password is incorrect')
        
        context ={}
        return render(request, 'main/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('main:login')


class IndexView(generic.TemplateView):
    template_name= "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs )
        reviews = REVIEW.objects.filter(is_active=True)
        blogs = BLOG.objects.filter(is_active=True)
        

        context["Reviews"] = reviews
        context["blogs"] = blogs

        return context

class BlogView(generic.ListView):
    model = BLOG
    template_name = "main/blog.html"
    paginate_by = 12

    def get_queryset(self):
        return super().get_queryset().filter(is_active = True)

class BlogDetailView(generic.DetailView):
    model = BLOG
    template_name = "main/blog-details.html"

class ReviewView(generic.ListView):
    model = REVIEW
    template_name = "main/categories.html"
    paginate_by = 20

    def get_queryset(self):
        return super().get_queryset().filter(is_active = True)

class ReviewDetailView(generic.DetailView):
    model = REVIEW
    template_name = "main/anime-details.html"

class BlogAddInfo(generic.FormView):
	template_name = "main/anime-watching.html"
	form_class = BlogForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Gracias por contribuir a la Comunidad con esta creación <3 te queremos mucho.')
		return super().form_valid(form)

class ReviewAddInfo(generic.FormView):
	template_name = "main/anime-watching2.html"
	form_class = ReviewForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Gracias por contribuir a la Comunidad con esta creación <3 te queremos mucho.')
		return super().form_valid(form)

# APARTADO PARA VISUALIZAR TUS MODELOS, EN ESTE CASO IndexView, BlogView, BlogDetailView, ReviewView, ReviewDetailView, BlogAddInfo & ReviewAddInfo

MangaWeb/main/templates/main/blog.html
<!-- Para cargar archivos estáticos -->
{% load static %} 
<!DOCTYPE html>
<html lang="zxx">

<!-- Encabezado de la Página -->
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Título de la Página -->
    <title>MANGA COMMUNITY Plus by SHUEISHA</title>

    <!-- Fuentes de Google -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Estilos Css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<!-- Fin de Encabezado -->

<!-- Inicio del Cuerpo de la Página -->
<body>
    <!-- Precargador de páginas -->
    <div id="preloder">
        <!-- Cargador de páginas -->
        <div class="loader"></div>
    </div>

    <!-- Inicio de la sección de Encabezado -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <!-- Url que redirige al index al tocar el logo de la página -->
                        <a href="{% url 'main:home' %}">
                            <img src="{% static 'img/logoM.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <!-- Urls que redirigen al usuario a cada uno de sus apartados -->
                                <li class="active"><a href="{% url 'main:home' %}">Inicio</a></li>
                                <li><a href="{% url 'main:reviews' %}">Reviews</a></li>
                                </li>
                                <li><a href="{% url 'main:blogs' %}">Blogs</a></li>
                                <li><a href="https://mangaplus.shueisha.co.jp/updates">Ver Mangas</a></li>
                                <li style="color: #b7b7b7; font-size: 15px; font-weight: 700;"> MICreador <span class="arrow_carrot-down"></span>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'main:blogaddinfo' %}">Crear Blogs</a></li>
                                        <li><a href="{% url 'main:reviewaddinfo' %}">Crear Reviews</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'main:logout' %}"><img src="{% static 'img/icon_logout (1).png' %}" alt="">
                        <a href="{% url 'main:login' %}"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Fin del encabezado -->

    <!-- Inicio del banner del Titulo de Blog PLUS con su bienvenida -->
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/barradeblog.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Blog PLUS</h2>
                        <p>Bienvenidos al Blog de la Comunidad de SHUEISHA.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Fin del banner del Titulo de Blog PLUS con su bienvenida -->

    <!-- Inicio de la sección de Blogs con sus urls respectivos -->
    
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        {% for obj in object_list %}
                        <div class={% if forloop.counter0|divisibleby:3 and forloop.counter0 < 6 or forloop.counter0 == 8 or forloop.counter0 == 11 %}"col-lg-12"{% else %}"col-lg-6 col-md-6 col-sm-6"{% endif %}>
                            <div class="blog__item {% if not forloop.counter0|divisibleby:3 and forloop.counter0 < 6 or forloop.counter0 != 8 and forloop.counter0 != 11 and forloop.counter0 > 5 %}small__item{% endif %} set-bg" {% if obj.image %}data-setbg="{{obj.image.url}}"{% endif %}>
                                <div class="blog__item__text">
                                    <p><span class="icon_calendar"></span> 30 de Mayo del 2022</p>
                                    <h4><a href="{%url 'main:blog' slug=obj.slug %}">{{obj.name}}</a></h4>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:6 %}
                        </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="row">
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Fin de la sección de Blogs con sus urls respectivos -->

    <!-- Inicio de la sección de Pie de Página con todos sus urls que redigiren al usuario a los diferentes apartados-->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="{% url 'main:home' %}"><img src="{% static 'img/logoM.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="{% url 'main:home' %}">Inicio</a></li>
                            <li><a href="{% url 'main:reviews' %}">Reviews</a></li>
                            <li><a href="{% url 'main:blogs' %}">Blog</a></li>
                            <li><a href="https://mangaplus.shueisha.co.jp/updates">Ver Mangas</a></li>
                            <li><a href="{% url 'main:blogaddinfo' %}">MICreador</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3" style="text-align: justify;text-justify: inter-word;">
                    <p><!-- Referencia de Derechos de Autor como Decorativo -->
                      Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los Derechos Reservados | Esta página web fue creada con fines educativos con mucho <i class="fa fa-heart" aria-hidden="true"></i> por <a href="https://www.twitch.tv/soyyairr" target="_blank">Yair Sánchez</a>
                      <!--  Referencia de Derechos de Autor como Decorativo --></p>

                  </div>
              </div>
          </div>
      </footer>
      <!-- Fin de la sección de Pie de Página con todos sus urls que redigiren al usuario a los diferentes apartados-->

    <!-- JavaScript Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
<!-- Fin del Cuerpo de la Página -->

</html>

MangaWeb/main/templates/main/login.html
<!-- OJO LEER PRIMERO ESTO!!!: ESTE APARTADO NO SE USO PERO SE DEJO CON EL FIN DE QUE MÁS ADELANTE SE PUEDA CREAR DICHA PARTE PARA INICIAR SESIÓN A LA PÁGINA -->

<!-- Para cargar archivos estáticos -->
{% load static %} 
<!DOCTYPE html>
<html lang="zxx">

<!-- Encabezado de la Página -->
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Título de la Página -->
    <title>MANGA COMMUNITY Plus by SHUEISHA</title>

    <!-- Fuentes de Google -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Estilos Css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<!-- Fin de Encabezado -->

<!-- Inicio del Cuerpo de la Página -->
<body>
    <!-- Precargador de páginas -->
    <div id="preloder">
        <!-- Cargador de páginas -->
        <div class="loader"></div>
    </div>

    <!-- Inicio de la sección de Encabezado -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'main:home' %}">
                            <img src="{% static 'img/logoM.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <!-- Urls que redirigen al usuario a cada uno de sus apartados -->
                                <li class="active"><a href="{% url 'main:home' %}">Inicio</a></li>
                                <li><a href="{% url 'main:reviews' %}">Reviews</a></li>
                                </li>
                                <li><a href="{% url 'main:blogs' %}">Blogs</a></li>
                                <li><a href="https://mangaplus.shueisha.co.jp/updates">Ver Mangas</a></li>
                                <li style="color: #b7b7b7; font-size: 15px; font-weight: 700;"> MICreador <span class="arrow_carrot-down"></span>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'main:blogaddinfo' %}">Crear Blogs</a></li>
                                        <li><a href="{% url 'main:reviewaddinfo' %}">Crear Reviews</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="header__right">
                        <a href="{% url 'main:logout' %}"><img src="{% static 'img/icon_logout (1).png' %}" alt="">
                        <a href="{% url 'main:login' %}"><span class="icon_profile"></span></a>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Fin del encabezado -->

    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/barradelogin.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Iniciar Sesión</h2>
                        <p>Bienvenido a La Comunidad Plus de SHUEISHA</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Login Section Begin -->
    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Iniciar Sesión</h3>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" name="username" placeholder="Nombre de Usuario..." class="form-control">
                                <span class="icon_profile"></span>
                            </div>
                            <div class="input__item">
                                <input type="password" name="password" placeholder="Contraseña..." class="form-control" >
                                <span class="icon_lock"></span>
                            </div>    
                                     <input class="site-btn" type="submit" value="Iniciar Sesión">
                            </div>
                        </form>
                    </div>
        {% for message in messages %}
            <p id="messages">{{message}}</p>
        {% endfor %}			
                <div class="col-lg-6">
                    <div class="login__register">
                        <h3>¿No tienes una cuenta?</h3>
                        <a href="{% url 'main:register' %}" class="primary-btn">Regístrate ahora</a>
                    </div>
                </div>
            </div>
            <div class="login__social">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6">
                        <div class="login__social__links">
                            <span>O</span>
                            <ul>
                                <li><a href="#" class="facebook"><i class="fa fa-facebook"></i> Inicia sesión con
                                    Facebook </a></li>
                                <li><a href="#" class="google"><i class="fa fa-google"></i> Inicia sesión con Google</a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i> Inicia sesión con Twitter</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->

    <!-- Inicio de la sección de Pie de Página con todos sus urls que redigiren al usuario a los diferentes apartados-->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="{% url 'main:home' %}"><img src="{% static 'img/logoM.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="{% url 'main:home' %}">Inicio</a></li>
                            <li><a href="{% url 'main:reviews' %}">Reviews</a></li>
                            <li><a href="{% url 'main:blogs' %}">Blog</a></li>
                            <li><a href="https://mangaplus.shueisha.co.jp/updates">Ver Mangas</a></li>
                            <li><a href="{% url 'main:blogaddinfo' %}">MICreador</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3" style="text-align: justify;text-justify: inter-word;">
                    <p><!-- Referencia de Derechos de Autor como Decorativo -->
                      Copyright &copy;<script>document.write(new Date().getFullYear());</script> Todos los Derechos Reservados | Esta página web fue creada con fines educativos con mucho <i class="fa fa-heart" aria-hidden="true"></i> por <a href="https://www.twitch.tv/soyyairr" target="_blank">Yair Sánchez</a>
                      <!--  Referencia de Derechos de Autor como Decorativo --></p>

                  </div>
              </div>
          </div>
      </footer>
      <!-- Fin de la sección de Pie de Página con todos sus urls que redigiren al usuario a los diferentes apartados-->

    <!-- JavaScript Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/player.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>



</body>
<!-- Fin del Cuerpo de la Página -->

</html>

MangaWeb/main/templates/main/main.html
<!-- APARTADO MAIN DE LA PLANTILLA DE LA PÁGINA -->

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>